/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg171213078_ecir_sulga_kod;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static pkg171213078_ecir_sulga_kod.ToBufferedImage.toBufferedImage;

/**
 *
 * @author ecome
 */
public class PreProcessingFrame extends javax.swing.JFrame {

    /**
     * Creates new form PreProcessingFrame
     */
    public PreProcessingFrame() {
        initComponents();
    }
    public Image lastImage;

    public PreProcessingFrame(Image lastImage) {
        initComponents();
        this.lastImage = lastImage;
        imageFinal.setIcon(new ImageIcon(lastImage));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbPreProsApprove = new javax.swing.JRadioButton();
        rbPreProsReject = new javax.swing.JRadioButton();
        cmbPrePros = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        imageFinal = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rbPreProsApprove);
        rbPreProsApprove.setText("Ön işleme uygulamak istiyorum.");
        rbPreProsApprove.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbPreProsApproveStateChanged(evt);
            }
        });
        rbPreProsApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPreProsApproveActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPreProsReject);
        rbPreProsReject.setSelected(true);
        rbPreProsReject.setText("Ön işleme Uygulamak istemiyorum.");
        rbPreProsReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPreProsRejectActionPerformed(evt);
            }
        });

        cmbPrePros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "Renkli resmi gri seviye dönüştürme", "Resimden istenilen bölgenin kesilip alınması", "Histogram oluşturma" }));
        cmbPrePros.setEnabled(false);
        cmbPrePros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPreProsİtemStateChanged(evt);
            }
        });
        cmbPrePros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPreProsActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resim Önizleme");

        imageFinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imageFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imageFinalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                imageFinalMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(imageFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imageFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btnNext.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnNext.setText("İleri");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbPreProsReject, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbPreProsApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPrePros, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 512, Short.MAX_VALUE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbPreProsApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbPreProsReject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPrePros, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbPreProsApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPreProsApproveActionPerformed

    }//GEN-LAST:event_rbPreProsApproveActionPerformed

    private void rbPreProsApproveStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbPreProsApproveStateChanged
        if (rbPreProsApprove.isSelected()) {
            cmbPrePros.setEnabled(true);
        } else {
            imageFinal.setIcon(new ImageIcon(lastImage));
            cmbPrePros.setEnabled(false);
        }
    }//GEN-LAST:event_rbPreProsApproveStateChanged

    int firstX;
    int firstY;
    int lastX;
    int lastY;


    private void rbPreProsRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPreProsRejectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPreProsRejectActionPerformed
    BufferedImage image;
    int width;
    int height;
    private void cmbPreProsİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPreProsİtemStateChanged


    }//GEN-LAST:event_cmbPreProsİtemStateChanged

    private void imageFinalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageFinalMousePressed
        if (cmbPrePros.getSelectedIndex() == 2) {
            firstX = evt.getX();
            firstY = evt.getY();
            this.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
        }
    }//GEN-LAST:event_imageFinalMousePressed

    private void imageFinalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageFinalMouseReleased
        if (cmbPrePros.getSelectedIndex() == 2) {
            lastX = evt.getX();
            lastY = evt.getY();
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            
            
            image = toBufferedImage(lastImage);
            BufferedImage cuttedImage=image.getSubimage(firstX, firstY, lastX-firstX, lastY-firstY);
            
            imageFinal.setIcon(new ImageIcon(cuttedImage.getScaledInstance(imageFinal.getWidth(), imageFinal.getHeight(), BufferedImage.SCALE_SMOOTH)));
            lastImage= cuttedImage.getScaledInstance(imageFinal.getWidth(), imageFinal.getHeight(), BufferedImage.SCALE_SMOOTH);
        }

    }//GEN-LAST:event_imageFinalMouseReleased

    private void cmbPreProsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPreProsActionPerformed
        image = toBufferedImage(lastImage);
        histogramPanel histogramPanel=new histogramPanel(image);
        if (cmbPrePros.getSelectedIndex() == 1) {
            
            width = image.getWidth();
            height = image.getHeight();
            for (int i = 0; i < height; i++) {
                for (int j = 0; j < width; j++) {
                    Color c = new Color(image.getRGB(j, i));
                    int red = (int) (c.getRed() * 0.299);
                    int green = (int) (c.getGreen() * 0.587);
                    int blue = (int) (c.getBlue() * 0.114);
                    Color newColor = new Color(red + green + blue, red + green + blue, red + green + blue);
                    image.setRGB(j, i, newColor.getRGB());
                }
            }
            imageFinal.setIcon(new ImageIcon(image));
            lastImage =image;
        } 
        else if (cmbPrePros.getSelectedIndex() == 2) 
        {
            JOptionPane.showMessageDialog(null, "Kesilecek bölüm için resmin bir ucundan basılı tutup kaydırın.", "bilgi", JOptionPane.OK_OPTION);
        }
        else if(cmbPrePros.getSelectedIndex() == 3)
        {
            
            histogramPanel.setMaximumSize(new Dimension(1000, 600));
            histogramPanel.setMinimumSize(new Dimension(1000, 600));
            histogramPanel.setVisible(true);
        }
    }//GEN-LAST:event_cmbPreProsActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        JFrame next= new FilterMenuFrame(lastImage);
        next.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreProcessingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreProcessingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbPrePros;
    private javax.swing.JLabel imageFinal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbPreProsApprove;
    private javax.swing.JRadioButton rbPreProsReject;
    // End of variables declaration//GEN-END:variables
}
